{% set version = "0.6.8" %}

package:
  name: dateutils
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/dateutils/dateutils-{{ version }}.tar.gz
  sha256: 15e564d9cd34e4260cf96625a3249c938c3aada2e5eaddf8218dd3fbc8dbdba4

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - dateadd = dateutils.dateadd:main
    - datediff = dateutils.datediff:main

requirements:
  build:
    - python <3
    - pip
  run:
    - python <3
    - python-dateutil
    - pytz

test:
  imports:
    - dateutils
  commands:
    - dateadd --help
    - datediff --help

about:
  home: https://pypi.org/project/dateutils
  license: BSD
  summary: Various utilities for working with date and datetime objects

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
