{% set version = "0.6.6" %}

package:
  name: dateutils
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/dateutils/dateutils-{{ version }}.tar.gz
  sha256: c94a8e77d743abac79ed91f99f5ef594a972a527e05145cbb7aba59beced8a71

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  entry_points:
    - dateadd = dateutils.dateadd:main
    - datediff = dateutils.datediff:main

requirements:
  build:
    - python <3
    - pip
  run:
    - python <3
    - python-dateutil
    - pytz

test:
  imports:
    - dateutils
  commands:
    - dateadd --help
    - datediff --help

about:
  home: https://pypi.org/project/dateutils
  license: BSD
  summary: Various utilities for working with date and datetime objects

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
