{% set version = "0.6.10" %}

package:
  name: dateutils
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/dateutils/dateutils-{{ version }}.tar.gz
  sha256: 860b3e40261085f56928f1454ee4d221856b56aa421c69a7df12067596ec0b26

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - dateadd = dateutils.dateadd:main
    - datediff = dateutils.datediff:main

requirements:
  build:
    - python <3
    - pip
  run:
    - python <3
    - python-dateutil
    - pytz

test:
  imports:
    - dateutils
  commands:
    - dateadd --help
    - datediff --help

about:
  home: https://pypi.org/project/dateutils
  license: BSD
  license_file: LICENSE
  summary: Various utilities for working with date and datetime objects

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
