{% set version = "0.6.12" %}

package:
  name: dateutils
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/dateutils/dateutils-{{ version }}.tar.gz
  sha256: 03dd90bcb21541bd4eb4b013637e4f1b5f944881c46cc6e4b67a6059e370e3f1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - dateadd = dateutils.dateadd:main
    - datediff = dateutils.datediff:main

requirements:
  build:
    - python >=3
    - pip
  run:
    - python >=3
    # - argparse only for py<27
    - python-dateutil
    - pytz

test:
  imports:
    - dateutils
  # we can re-enable pip check when upstream drops 2.6 or they add it as a py26 dep only.
  # or, better yet, pip understands that it is in the std library there this hack of installing stubs needs to end!
  # requires:
  #   - pip
  commands:
    # - pip check
    - dateadd --help
    - datediff --help

about:
  home: https://pypi.org/project/dateutils
  license: 0BSD
  license_file: LICENSE
  summary: Various utilities for working with date and datetime objects

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
