# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_python2.7

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "ztZLj1go+ZB+XJ1gcmsgV/v3jO25YP7ZLkZbnL1ORkB9aNy2sjh6t5evvPgdWqVfsvKWY4fZn/B3lxjUX/KK6mw4nmN6QCuyyBYdMip6lYA2L7CMqVVIymk0tk3CWpC6n5B7qSKfyBnuTFxTihp5iOpsk/xRd51vIw3FywSyhxzMd8v9jm2lHoCmu9qLSDfMUud+KdWUFJWWzygsDDrRK485IH9pVmWr05Hg6YFT0r8b+NANOGANmhwPbj9NBg89v97jL0qbfRpk0gkhrSzDfKwkDj/guyNy5r7Whg3q8bY4nbFdda45n1FxAyaaSt999ulwHuoJlSefWkRwJ4n9YlTYaAl0BbI7f/bLspTQEkeOP+U2VjlqyXmEJ0+15zwLbaeuYeRdItJ/oZxmBzLqoo/3orS4MbYwi4dHMBrqGeB6XNebw4SGhNrlZ5Wj5DILscLgcIrX4c+5Pyn4Zw9XfhNzW7mwzbAGBfx/RXyVSnYIKcQRiHp01xZEBoAjcSgDNqHH4CDaj1OdlfChXY1bO9Uv3b5ETuDoT9K8iPRTw7vlVwHfzKDkAuus/OPktSzJOkjW3rhZgfxyiaxBeVKw9w58NywItOy7MtqAy1laf0R0fAYRs9Qh1a2utkDcThHRMBTfhuCblRzRh9Tyn6rfXqkfwKFN9hjlwfkhimCoWA0="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
