travis:
  secure:
    BINSTAR_TOKEN: ztZLj1go+ZB+XJ1gcmsgV/v3jO25YP7ZLkZbnL1ORkB9aNy2sjh6t5evvPgdWqVfsvKWY4fZn/B3lxjUX/KK6mw4nmN6QCuyyBYdMip6lYA2L7CMqVVIymk0tk3CWpC6n5B7qSKfyBnuTFxTihp5iOpsk/xRd51vIw3FywSyhxzMd8v9jm2lHoCmu9qLSDfMUud+KdWUFJWWzygsDDrRK485IH9pVmWr05Hg6YFT0r8b+NANOGANmhwPbj9NBg89v97jL0qbfRpk0gkhrSzDfKwkDj/guyNy5r7Whg3q8bY4nbFdda45n1FxAyaaSt999ulwHuoJlSefWkRwJ4n9YlTYaAl0BbI7f/bLspTQEkeOP+U2VjlqyXmEJ0+15zwLbaeuYeRdItJ/oZxmBzLqoo/3orS4MbYwi4dHMBrqGeB6XNebw4SGhNrlZ5Wj5DILscLgcIrX4c+5Pyn4Zw9XfhNzW7mwzbAGBfx/RXyVSnYIKcQRiHp01xZEBoAjcSgDNqHH4CDaj1OdlfChXY1bO9Uv3b5ETuDoT9K8iPRTw7vlVwHfzKDkAuus/OPktSzJOkjW3rhZgfxyiaxBeVKw9w58NywItOy7MtqAy1laf0R0fAYRs9Qh1a2utkDcThHRMBTfhuCblRzRh9Tyn6rfXqkfwKFN9hjlwfkhimCoWA0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
