travis:
  secure:
    BINSTAR_TOKEN: UdgsPdNrPHb90AsKVZB4RPIo8T7MdCwTbLS/kUoIUAn/WyrxidHzpTQo4krGsFiP6384kX5dugeCrAAFGMOPV7Be/QuZWFGwWmDJQTMCZDmnci1VGDl7v11vpJ6iZhu/N7dL/idiXT991l+dDUOuKxkQRgH2UEG9ZnnyMkijegm86AIaqroLDXtnyepYN/gVA1M5hpS2fYJE/0pou4ydpuw4u0Vz6vI1QHzbP/iXBYf8bfzzyTw/uBjUDsDFsxOzMQtrcDcKlvI2oxsPqZcNhus3fZ4ntINWbj4wd9WrSrr6xNmX1qlmMJiU0WNxRiWaDU+hpz4/vNGqc6MRNFPSBFD1sqaQ3LWjf0ana6FUhAy/wVTlsRudVPgVXCB+YIy3HR5m3zUO3TDL5lmN6taRIxOIwG8B9eO2VsmVj0K7wZX8uDHyRA2XmwngoEFPjCcSV53GvP6L4T5RlIs1Pdiaf2PaD4tGmbWCJlxXUEo8fTmDfhuhwMJeLuK7xiwVlRU1QTjugVSfr+AaGeemaXaq7rqe2K8lLtwU2w8+vUHCPeC1QZ0iCglOcBKpA9PCeF5IxNzLNqdB869WUPn4XTiZ14T3XzO+fQEDLzkWXjuXMXXRMRy9scncaCpIMay5LUbwOaNs64UA+lpt6Tyte56OgmRKdsRC0vk2cPLPeUx0WFs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
